T: 16
T_train: null
amp: true
batch_size: 16
cooldown_epochs: 10
cutmix: 0.0
cutmix_minmax: null
data_path: ''
dataset: cifar10dvs
decay_epochs: 20
decay_rate: 0.1
device: cuda:0
dist_url: env://
distributed: false
epoch_repeats: 0.0
epochs: 96
experiment: ''
flblocks: 4
log_wandb: false
lr: 0.005
lr_cycle_limit: 1
lr_cycle_mul: 1.0
lr_noise: null
lr_noise_pct: 0.67
lr_noise_std: 1.0
min_lr: 2.0e-05
mixup: 0.5
mixup_mode: batch
mixup_off_epoch: 0
mixup_prob: 0.5
mixup_switch_prob: 0.5
model: swformer
momentum: 0.9
num_classes: 10
opt: adamw
opt_betas: null
opt_eps: 1.0e-08
output_dir: ./logs
patience_epochs: 10
print_freq: 256
resume: ''
sched: cosine
seed: 1
smoothing: 0.1
start_epoch: 0
sync_bn: false
test_only: false
warmup_epochs: 10
warmup_lr: 1.0e-05
weight_decay: 0.06
workers: 4
world_size: 1
